[build]
  publish = "build"
  command = "CI=false npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "http://0.0.0.0:8000 "
  CI = "false"
  GENERATE_SOURCEMAP = "false"
