[build]
  publish = "build"
  command = "CI=false npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://promo-gb.duckdns.org"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
